### ISSUE TITLE
No way to install spectra, following the instructions in Github

### ISSUE THREAD

**Issue by jmigartua** [Mathpix/spectra#1]
Hi there,

I am trying to install *spectra* following the instructions in [Github](https://github.com/Mathpix/spectra), which I understand is only to run `npm install -g @mathpix/spectra`. This is the error message I obtain, once and again:

`The authenticity of host 'github.com (140.82.121.3)' can't be established.pectra@0.0.6 checking installable status`
`RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.`
`⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ fetchMetadata: sill resolveWithNewModule @mathpix/spectra@0.0.6 checking installable status`
`npm ERR! Error while executing:`
`npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/montanaflynn/eleventy.git`
`npm ERR!` 
`npm ERR! Host key verification failed.`
`npm ERR! fatal: Could not read from remote repository.`
`npm ERR!` 
`npm ERR! Please make sure you have the correct access rights`
`npm ERR! and the repository exists.`
`npm ERR!` 
`npm ERR! exited with error code: 128`

`npm ERR! A complete log of this run can be found in:` 
`npm ERR!     path_to_the_log_file____logs/2021-02-05T05_07_16_988Z-debug.log`

I would very much appreciate some clue to solve this problem, perhaps only mine because I have not too much experience on this kind of things.

Many thanks for your time and effort!!!

Josu

**Comment by montanaflynn** [comment]
Hello @jmigartua, thanks for letting us know about the problem! It was happening because one of the dependencies required git and ssh to be set up before running the installation. I have released a new version which should not have this requirement. 

Can you try to install spectra again? 

`npm install -g @mathpix/spectra`

**Comment by jmigartua** [comment]
Hi @montanaflynn,

thanks!!!! it now works perfectly!

All the best!!

Josu
